module.exports = [
    {
        city: "New York",
        growth_from_2000_to_2013: "4.8%",
        lat: 40.7127837,
        lng: -74.0059413,
        population: "8405837",
        rank: "1",
        admin_name: "New York",
    },
        {
            city: "Delhi", 
            lat: "28.6600", 
            lng: "77.2300", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Delhi", 
            "capital": "admin", 
            "population": "29617000", 
            "population_proper": "16753235"
        }, 
        {
            city: "Mumbai", 
            lat: "18.9667", 
            lng: "72.8333", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "admin", 
            "population": "23355000", 
            "population_proper": "12478447"
        }, 
        {
            city: "Kolkata", 
            lat: "22.5411", 
            lng: "88.3378", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "West Bengal", 
            "capital": "admin", 
            "population": "17560000", 
            "population_proper": "4496694"
        }, 
        {
            city: "Bangalore", 
            lat: "12.9699", 
            lng: "77.5980", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Karnataka", 
            "capital": "admin", 
            "population": "13707000", 
            "population_proper": "8443675"
        }, 
        {
            city: "Chennai", 
            lat: "13.0825", 
            lng: "80.2750", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Tamil Nadu", 
            "capital": "admin", 
            "population": "11324000", 
            "population_proper": "6727000"
        }, 
        {
            city: "Hyderabad", 
            lat: "17.3667", 
            lng: "78.4667", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Telangana", 
            "capital": "admin", 
            "population": "9746000", 
            "population_proper": "6993262"
        }, 
        {
            city: "Pune", 
            lat: "18.5196", 
            lng: "73.8553", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "7764000", 
            "population_proper": "3124458"
        }, 
        {
            city: "Ahmadabad", 
            lat: "23.0300", 
            lng: "72.5800", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Gujarat", 
            "capital": "minor", 
            "population": "7410000", 
            "population_proper": "5570585"
        }, 
        {
            city: "S\u016brat", 
            lat: "21.1700", 
            lng: "72.8300", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Gujarat", 
            "capital": "", 
            "population": "5807000", 
            "population_proper": "4466826"
        }, 
        
        {
            city: "Jaipur", 
            lat: "26.9167", 
            lng: "75.8667", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Rajasthan", 
            "capital": "admin", 
            "population": "3073350", 
            "population_proper": "3073350"
        }, 
        {
            city: "Cawnpore", 
            lat: "26.4725", 
            lng: "80.3311", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "2701324", 
            "population_proper": "2701324"
        }, 
        {
            city: "Mirzapur", 
            lat: "25.1500", 
            lng: "82.5800", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "2496970", 
            "population_proper": "2496970"
        }, 
        {
            city: "Nagpur", 
            lat: "21.1539", 
            lng: "79.0831", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "2405665", 
            "population_proper": "2405665"
        }, 
        {
            city: "Ghaziabad", 
            lat: "28.6667", 
            lng: "77.4167", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "2381452", 
            "population_proper": "2381452"
        }, 
        {
            city: "Indore", 
            lat: "22.7206", 
            lng: "75.8472", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Madhya Pradesh", 
            "capital": "", 
            "population": "2201927", 
            "population_proper": "2201927"
        }, 
        {
            city: "Vadodara", 
            lat: "22.3000", 
            lng: "73.2000", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Gujarat", 
            "capital": "", 
            "population": "2065771", 
            "population_proper": "2065771"
        }, 
        {
            city: "Vishakhapatnam", 
            lat: "17.7333", 
            lng: "83.3167", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Andhra Pradesh", 
            "capital": "", 
            "population": "2035922", 
            "population_proper": "2035922"
        }, 
        {
            city: "Bhopal", 
            lat: "23.2500", 
            lng: "77.4167", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Madhya Pradesh", 
            "capital": "admin", 
            "population": "1883381", 
            "population_proper": "1883381"
        }, 
        {
            city: "Chinchvad", 
            lat: "18.6278", 
            lng: "73.8131", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "1729320", 
            "population_proper": "1729320"
        }, 
        {
            city: "Patna", 
            lat: "25.6100", 
            lng: "85.1414", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Bihar", 
            "capital": "admin", 
            "population": "1684222", 
            "population_proper": "1684222"
        }, 
        {
            city: "Ludhiana", 
            lat: "30.9083", 
            lng: "75.8486", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Punjab", 
            "capital": "", 
            "population": "1649000", 
            "population_proper": "1545368"
        }, 
        {
            city: "agra", 
            lat: "27.1800", 
            lng: "78.0200", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "1585705", 
            "population_proper": "1585705"
        }, 
        {
            city: "Kalyan", 
            lat: "19.2502", 
            lng: "73.1602", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "1576614", 
            "population_proper": "1576614"
        }, 
        {
            city: "Madurai", 
            lat: "9.9197", 
            lng: "78.1194", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Tamil Nadu", 
            "capital": "minor", 
            "population": "1561129", 
            "population_proper": "1561129"
        }, 
        {
            city: "Jamshedpur", 
            lat: "22.8000", 
            lng: "86.1833", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Jharkhand", 
            "capital": "", 
            "population": "1558000", 
            "population_proper": "1558000"
        }, 
        {
            city: "Nasik", 
            lat: "20.0000", 
            lng: "73.7833", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "1486053", 
            "population_proper": "1486053"
        }, 
        {
            city: "Faridabad", 
            lat: "28.4333", 
            lng: "77.3167", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Haryana", 
            "capital": "", 
            "population": "1394000", 
            "population_proper": "1394000"
        }, 
        {
            city: "Aurangabad", 
            lat: "19.8800", 
            lng: "75.3200", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "1371330", 
            "population_proper": "1371330"
        }, 
        {
            city: "Rajkot", 
            lat: "22.2969", 
            lng: "70.7984", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Gujarat", 
            "capital": "", 
            "population": "1335397", 
            "population_proper": "1335397"
        }, 
        {
            city: "Meerut", 
            lat: "28.9900", 
            lng: "77.7000", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "1305429", 
            "population_proper": "1305429"
        }, 
        {
            city: "Jabalpur", 
            lat: "23.1667", 
            lng: "79.9333", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Madhya Pradesh", 
            "capital": "", 
            "population": "1267564", 
            "population_proper": "1267564"
        }, 
        {
            city: "Thane", 
            lat: "19.1800", 
            lng: "72.9633", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "1261517", 
            "population_proper": "1261517"
        }, 
        {
            city: "Dhanbad", 
            lat: "23.7928", 
            lng: "86.4350", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Jharkhand", 
            "capital": "", 
            "population": "1246000", 
            "population_proper": "219636"
        }, 
        {
            city: "Allahabad", 
            lat: "25.4550", 
            lng: "81.8400", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "1201000", 
            "population_proper": "1073438"
        }, 
        {
            city: "Varanasi", 
            lat: "25.3189", 
            lng: "83.0128", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "1198491", 
            "population_proper": "1198491"
        }, 
        {
            city: "Srinagar", 
            lat: "34.0911", 
            lng: "74.8061", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Jammu and Kashmir", 
            "capital": "admin", 
            "population": "1180570", 
            "population_proper": "1180570"
        }, 
        {
            city: "Amritsar", 
            lat: "31.6167", 
            lng: "74.8500", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Punjab", 
            "capital": "", 
            "population": "1132383", 
            "population_proper": "1132383"
        }, 
        {
            city: "Aligarh", 
            lat: "27.8800", 
            lng: "78.0800", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "1131160", 
            "population_proper": "1131160"
        }, 
        {
            city: "Bhiwandi", 
            lat: "19.3000", 
            lng: "73.0667", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "1125898", 
            "population_proper": "1125898"
        }, 
        {
            city: "Gwalior", 
            lat: "26.2150", 
            lng: "78.1931", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Madhya Pradesh", 
            "capital": "", 
            "population": "1101981", 
            "population_proper": "1101981"
        }, 
        {
            city: "Bhilai", 
            lat: "21.2167", 
            lng: "81.4333", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Chhattisgarh", 
            "capital": "", 
            "population": "1097000", 
            "population_proper": "1097000"
        }, 
        {
            city: "Haora", 
            lat: "22.5900", 
            lng: "88.3100", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "West Bengal", 
            "capital": "", 
            "population": "1077075", 
            "population_proper": "1077075"
        }, 
        {
            city: "Ranchi", 
            lat: "23.3556", 
            lng: "85.3347", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Jharkhand", 
            "capital": "admin", 
            "population": "1073440", 
            "population_proper": "1073440"
        }, 
        {
            city: "Bezwada", 
            lat: "16.5167", 
            lng: "80.6167", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Andhra Pradesh", 
            "capital": "", 
            "population": "1048240", 
            "population_proper": "1048240"
        }, 
        {
            city: "Chandigarh", 
            lat: "30.7353", 
            lng: "76.7911", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Chandigarh", 
            "capital": "admin", 
            "population": "1026459", 
            "population_proper": "1026459"
        }, 
        {
            city: "Mysore", 
            lat: "12.3086", 
            lng: "76.6531", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Karnataka", 
            "capital": "", 
            "population": "1014227", 
            "population_proper": "1014227"
        }, 
        {
            city: "Raipur", 
            lat: "21.2379", 
            lng: "81.6337", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Chhattisgarh", 
            "capital": "admin", 
            "population": "1010087", 
            "population_proper": "1010087"
        }, 
        {
            city: "Kota", 
            lat: "25.1800", 
            lng: "75.8300", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Rajasthan", 
            "capital": "", 
            "population": "1001694", 
            "population_proper": "1001694"
        }, 
        {
            city: "Bareilly", 
            lat: "28.3640", 
            lng: "79.4150", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "1000000", 
            "population_proper": "1000000"
        }, 
        {
            city: "Jodhpur", 
            lat: "26.2918", 
            lng: "73.0168", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Rajasthan", 
            "capital": "", 
            "population": "995000", 
            "population_proper": "921476"
        }, 
        {
            city: "Coimbatore", 
            lat: "11.0000", 
            lng: "76.9667", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Tamil Nadu", 
            "capital": "", 
            "population": "959823", 
            "population_proper": "959823"
        }, 
        {
            city: "Dispur", 
            lat: "26.1500", 
            lng: "91.7700", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Assam", 
            "capital": "admin", 
            "population": "957352", 
            "population_proper": "957352"
        }, 
        {
            city: "Guwahati", 
            lat: "26.1667", 
            lng: "91.7667", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Assam", 
            "capital": "", 
            "population": "957352", 
            "population_proper": "957352"
        }, 
        {
            city: "Solapur", 
            lat: "17.6833", 
            lng: "75.9167", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "951558", 
            "population_proper": "951558"
        }, 
        {
            city: "Trichinopoly", 
            lat: "10.8269", 
            lng: "78.6928", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Tamil Nadu", 
            "capital": "", 
            "population": "916857", 
            "population_proper": "916857"
        }, 
        {
            city: "Hubli", 
            lat: "15.3600", 
            lng: "75.1250", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Karnataka", 
            "capital": "", 
            "population": "890000", 
            "population_proper": "792804"
        }, 
        {
            city: "Jalandhar", 
            lat: "31.3256", 
            lng: "75.5792", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Punjab", 
            "capital": "", 
            "population": "873725", 
            "population_proper": "873725"
        }, 
        {
            city: "Bhubaneshwar", 
            lat: "20.2644", 
            lng: "85.8281", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Odisha", 
            "capital": "admin", 
            "population": "837737", 
            "population_proper": "837737"
        }, 
        {
            city: "Bhayandar", 
            lat: "19.3000", 
            lng: "72.8500", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "814655", 
            "population_proper": "814655"
        }, 
        {
            city: "Moradabad", 
            lat: "28.8418", 
            lng: "78.7568", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "787000", 
            "population_proper": "721139"
        }, 
        {
            city: "Kolhapur", 
            lat: "16.7000", 
            lng: "74.2333", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Maharashtra", 
            "capital": "", 
            "population": "750000", 
            "population_proper": "561841"
        }, 
        {
            city: "Thiruvananthapuram", 
            lat: "8.5000", 
            lng: "76.8997", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Kerala", 
            "capital": "admin", 
            "population": "743691", 
            "population_proper": "743691"
        }, 
        {
            city: "Saharanpur", 
            lat: "29.9640", 
            lng: "77.5460", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Uttar Pradesh", 
            "capital": "", 
            "population": "705478", 
            "population_proper": "705478"
        }, 
        {
            city: "Warangal", 
            lat: "17.9756", 
            lng: "79.6011", 
            "country": "India", 
            "iso2": "IN", 
            admin_name: "Telangana", 
            "capital": "", 
            "population": "704570", 
            "population_proper": "704570"
        }, 
    
];
